---
- name: Install wordpress
  remote_user: ansible
  hosts: webservers
  become: yes
  vars_files:
    - ./inventory/production/group_vars/t2micro.yml
    - ./inventory/production/group_vars/webservers.yml
  roles:
    - docker
    - wordpress

