CREATE TABLE IF NOT EXISTS Students (
ID INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
Student VARCHAR(30) NOT NULL,
StudentId INT
);
CREATE UNIQUE INDEX unique_StudentId ON Students (StudentId);

CREATE TABLE IF NOT EXISTS Result (
ID INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
StudentId INT,
Task1 VARCHAR(20) NOT NULL,
Task2 VARCHAR(20) NOT NULL,
Task3 VARCHAR(20) NOT NULL,
Task4 VARCHAR(20) NOT NULL,
Task5 VARCHAR(20) NOT NULL,
FOREIGN KEY (StudentId)  REFERENCES Students (StudentId)
);