pipeline {
    agent {
            label 'agent3'
          }
    environment {
        PASSWORD = credentials('ansible-secret')
    }
    stages {
        stage('1-Build') {
            steps {
                echo "Start of Stage Build"
                dir('task6/EXTRA/ansible') {
                    sh """
                        pwd
                        touch secret
                        ls -la
                    """
                    cat "${PASSWORD}" > secret
                }
                echo "End of Stage Build"
            }
        }
        stage('2-Test') {
            steps {
                echo "Start of Stage Test"
                sh """
                    pwd
                    docker ps
                """
                echo "End of Stage Test"
            }
        }
        stage('3-Deploy') {
            steps {
                echo "Start of Stage Deploy"
                echo "Deploying......."
                echo "End of Stage Deploy"
            }
        }
    }
}