pipeline {
    agent {
            label 'agent3'
          }
    stages {
        stage('1-Build') {
            steps {
                echo "Start of Stage Build"
                sh "pwd"
                dir('task3/3.2/') {
                    sh "pwd"
                    sh 'ls -la'
                }
                echo "End of Stage Build"
            }
        }
        stage('2-Test') {
            steps {
                echo "Start of Stage Test"
                sh "pwd"
                sh 'ls -la'
                echo "End of Stage Test"
            }
        }
        stage('3-Deploy') {
            steps {
                echo "Start of Stage Deploy"
                echo "Deploying......."
                echo "End of Stage Deploy"
            }
        }
    }
}